-- @description Chord Tools
-- @author YS
-- @version 1.0
-- @changelog
--   Initial release
-- @metapackage
-- @provides
--   [main=midi_editor] Chord Tools/YS_Chord Tools.lua
--   Chord Tools/keyboard.jpg

-- Licensed under the GNU GPL v3