-- @description Chord Tools
-- @author YS
-- @version 1.0.3
-- @changelog
--   优化代码以兼容 ReaImGui 0.10
-- @metapackage
-- @provides
--   [main=midi_editor] Chord Tools/YS_Chord Tools.lua
--   Chord Tools/keyboard.jpg

-- Licensed under the GNU GPL v3