-- @description Chord Tools
-- @author YS
-- @version 1.0.2
-- @changelog
--   增加hold模式，以及和弦识别范围扩大，不同的排列以及省略音的识别。
--   Added hold mode, expanded chord recognition range, and improved detection of different voicings and omitted notes.
-- @metapackage
-- @provides
--   [main=midi_editor] Chord Tools/YS_Chord Tools.lua
--   Chord Tools/keyboard.jpg

-- Licensed under the GNU GPL v3