-- @description Chord Tools Bundle
-- @author YS
-- @version 1.0
-- @changelog
--   Initial release
-- @links
--   https://www.soundengine.cn/user/%E5%86%8D%E8%A3%9C%E4%B8%80%E5%88%80
--   https://github.com/zaibuyidao/ReaScripts
-- @metapackage
-- @provides
--   [main=midi_editor] Chord Tools/YS_Chord Tools.lua
--   Chord Tools/keyboard.jpg

-- Licensed under the GNU GPL v3