-- @description pattern 节奏生成器 Bundle
-- @author YS
-- @version 1.0
-- @changelog
--   Initial release
-- @metapackage
-- @provides
--   [main=midi_editor] Pattern Rhythm Generator/YS_pattern 节奏生成器.lua
--   Pattern Rhythm Generator/*.jpg

-- Licensed under the GNU GPL v3